export const SCREEN_WIDTH = 1280;
export const SCREEN_HEIGHT = 720;

export const GAME_OBJECT_POSITION_X_ROUND_NUMBER = 100;
export const GAME_OBJECT_POSITION_Y_ROUND_NUMBER = 250;

export const GAME_OBJECT_POSITION_X_REQUESTED_ACTION = 700;
export const GAME_OBJECT_POSITION_Y_REQUESTED_ACTION = 250;

export const GAME_OBJECT_POSITION_X_CARD_STACKS_CONTAINER = 660;
export const GAME_OBJECT_POSITION_Y_CARD_STACKS_CONTAINER = 500;
